module.exports.authService = require('./auth.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.productService = require('./product.service')
module.exports.brandService = require('./brand.service')
module.exports.newService = require('./new.service')
